name: Test Code
on:
  pull_request:
  push:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test-code:
    environment:
      name: QA
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install Dependencies
        run: npm install
      - name: Test Lint
        run: npm run lint
      - name: Test coverage
        run: npm run test

      - name: Set Homepage
        run: npm run setHomepage

      - name: Build
        run: CI=false npm run build

      - name: deploy to QA env --> Netlify
        run: netlify deploy --prod --auth ${{ secrets.NETLIFY_TOKEN }} --site ${{ secrets.SITE_ID }}

      - name: Create PR
        uses: medlypharmacy/create-pr-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HEAD_BRANCH: main
          BASE_BRANCH: develop
